### ISSUE TITLE
I get a error

### ISSUE THREAD

**Issue by Pedrvisk** [DDDinggo22/Osu-Bot-V3#1]
When I open Osu! Bot V3 x86 it says that it was not possible to find the entry point of the GetDpiForWindown procedure in the dynamic link library USER32.dll

**Comment by TheCodingNina** [comment]
Hi,
If I understand your problem correctly, you are unable to start the executable.
And instead it will show a message that says it could not find the entry point of the GetDpiForWindows procedure in USER32.dll?

The GetDpiForWindows function is used to retrieve the dpi settings to correctly display any Direct2D elements.
This function appears to be minimum supported from Windows 10, version 1607.

If your windows version is higher, then it might be possible that either:
- Some application is accessing the library wrong.  
   Reinstalling the application should fix this problem most of the time.
- Or the library might broken (rare case).  
   Try running windows repair.

**Comment by Pedrvisk** [comment]
Ok thank you

**Comment by oSumAtrIX** [comment]
Any way to run it on win7?
